/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Customer;
import Business.Flight;
import Business.SeatAssignment;
import Business.Ticket;
import Business.TravelAgency;
import java.awt.CardLayout;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author aelinadas
 */
public class BookASeatJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookASeatJPanel
     */
    private JPanel displayPanel;
    private TravelAgency travelAgency;
    private Flight flight;
    private String userName;

    BookASeatJPanel(TravelAgency travelAgency, JPanel displayPanel, Flight flight, String userName) {
        initComponents();
        this.travelAgency = travelAgency;
        this.displayPanel = displayPanel;
        this.flight = flight;
        this.userName = userName;
        if (userName.equals("")) {
            usernameTxtField.setEnabled(true);
            usernameTxtField.setEditable(true);
        } else {
            usernameTxtField.setText(userName.trim());
            usernameTxtField.setEnabled(false);
            usernameTxtField.setEditable(false);
        }

        populateDetails(flight);
        seatNumberComboBox.removeAllItems();
        seatNumberComboBox.setEnabled(false);
        seatTypeBtn.setEnabled(false);

    }

    public void populateDetails(Flight flight) {
        flightNumberTextField.setText(flight.getFlightNumber());
        departureTextField.setText(flight.getDepartureLocation());
        arrivalTextField.setText(flight.getArrivalLocation());
        dateTextField.setText(flight.getDate());
        timeTextField.setText(flight.getFlightTime());
        durationTextField.setText(flight.getFlightDuration() + "");
//        if (flight.isIsAvailable()) {
//            availabiltyTextField.setText("Available");
//        } else {
//            availabiltyTextField.setText("Canceled");
//        }
        priceTextField.setText(flight.getPrice() + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        flightNumberTextField = new javax.swing.JTextField();
        departureTextField = new javax.swing.JTextField();
        arrivalTextField = new javax.swing.JTextField();
        dateTextField = new javax.swing.JTextField();
        timeTextField = new javax.swing.JTextField();
        durationTextField = new javax.swing.JTextField();
        priceTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        reserveBtn = new javax.swing.JButton();
        seatTypeComboBox = new javax.swing.JComboBox<>();
        seatNumberComboBox = new javax.swing.JComboBox<>();
        showSeatsBtn = new javax.swing.JButton();
        seatTypeBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        usernameTxtField = new javax.swing.JTextField();

        setEnabled(false);

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Flight Time:");

        jLabel3.setText("Departure Location:");

        jLabel4.setText("Arrival Location:");

        jLabel5.setText("Date of Travel:");

        jLabel6.setText("Flight Number:");

        jLabel7.setText("Flight Duration:");

        jLabel9.setText("Price:");

        flightNumberTextField.setEditable(false);
        flightNumberTextField.setEnabled(false);

        departureTextField.setEditable(false);
        departureTextField.setEnabled(false);

        arrivalTextField.setEditable(false);
        arrivalTextField.setEnabled(false);

        dateTextField.setEditable(false);
        dateTextField.setEnabled(false);
        dateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextFieldActionPerformed(evt);
            }
        });

        timeTextField.setEditable(false);
        timeTextField.setEnabled(false);
        timeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeTextFieldActionPerformed(evt);
            }
        });

        durationTextField.setEditable(false);
        durationTextField.setEnabled(false);

        priceTextField.setEditable(false);
        priceTextField.setEnabled(false);

        jLabel13.setText("User Name:");

        reserveBtn.setText("Reserve");
        reserveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveBtnActionPerformed(evt);
            }
        });

        seatTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Window", "Middle", "Aisle" }));

        seatNumberComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        showSeatsBtn.setText("Show Seats");
        showSeatsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSeatsBtnActionPerformed(evt);
            }
        });

        seatTypeBtn.setText("Change Seat Type");
        seatTypeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatTypeBtnActionPerformed(evt);
            }
        });

        jLabel10.setText("Seat Type:");

        jLabel11.setText("Seat Number");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("RESERVE SEAT");
        jLabel8.setToolTipText("");

        jLabel1.setText("(USD)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(169, 169, 169)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(302, 302, 302)
                                .addComponent(reserveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(usernameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(seatTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(seatNumberComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(departureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(arrivalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(flightNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(timeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(durationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(showSeatsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seatTypeBtn)))))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(usernameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(flightNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(departureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(durationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel1))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arrivalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(showSeatsBtn)
                    .addComponent(seatTypeBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatNumberComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(142, 142, 142)
                .addComponent(reserveBtn)
                .addGap(0, 151, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        displayPanel.remove(this);
        CardLayout cardLayout = (CardLayout) displayPanel.getLayout();
        cardLayout.previous(displayPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void dateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTextFieldActionPerformed

    private void timeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeTextFieldActionPerformed

    public boolean isOnDirectory(String userName) {
        boolean isCustomer = false;
        for (Customer customer : travelAgency.getCustomerDirectory()) {
            if (customer.getUserName().equals(userName)) {
                isCustomer = true;
                break;
            }
        }
        return isCustomer;
    }
    private void reserveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveBtnActionPerformed
        // TODO add your handling code here:

        if ((!usernameTxtField.getText().equals("") || !(usernameTxtField.getText() == null)) && isOnDirectory(usernameTxtField.getText().trim())) {
            if (seatNumberComboBox.getSelectedItem() != null) {
                String seatNumber = seatNumberComboBox.getSelectedItem().toString();
                String ticketNumber = usernameTxtField.getText().trim().split("@")[0] + seatNumber;
                for (SeatAssignment seatAssignment : flight.getSeatAssignmentDirectory()) {
                    if (seatAssignment.getSeatNumber().equalsIgnoreCase(seatNumber)) {
                        seatAssignment.setIsAvailable(false);
                    }
                }
                SimpleDateFormat simpleDateFormat = new SimpleDateFormat("mm/dd/yyyy HH:mm:ss");
                Date bookingDate = new Date();
                String Date = simpleDateFormat.format(bookingDate);
                try {
                    bookingDate = simpleDateFormat.parse(Date);
                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(null, "Inavlid date");
                }
                Ticket ticket = new Ticket(flightNumberTextField.getText(), departureTextField.getText(), arrivalTextField.getText(), Double.parseDouble(durationTextField.getText()), dateTextField.getText(), timeTextField.getText(), "Available", Double.parseDouble(priceTextField.getText()), usernameTxtField.getText().trim(), ticketNumber, bookingDate, seatNumber);
                System.out.println(ticket);
                JOptionPane.showMessageDialog(null, "Thank You for Booking With us. Your Ticket Number is " + ticketNumber);
                for (Customer customer : travelAgency.getCustomerDirectory()) {
                    if (customer.getUserName().equalsIgnoreCase(usernameTxtField.getText())) {
                        customer.setTicket(ticket);
                        break;
                    }
                }
                backBtnActionPerformed(evt);
            } else {
                JOptionPane.showMessageDialog(null, "Please select a preferred seat");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Please select a valid username to book ticket");
        }
    }//GEN-LAST:event_reserveBtnActionPerformed

    private void showSeatsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSeatsBtnActionPerformed
        // TODO add your handling code here:
        String seatType = (String) seatTypeComboBox.getSelectedItem();
        if (seatType.equalsIgnoreCase("Window")) {
            for (SeatAssignment seatAssignment : flight.getSeatAssignmentDirectory()) {
                if (seatAssignment.getSeatType().equalsIgnoreCase("Window") && seatAssignment.isIsAvailable()) {
                    seatNumberComboBox.addItem(seatAssignment.getSeatNumber());
                }
            }
        }
        if (seatType.equalsIgnoreCase("Middle")) {
            for (SeatAssignment seatAssignment : flight.getSeatAssignmentDirectory()) {
                if (seatAssignment.getSeatType().equalsIgnoreCase("Middle") && seatAssignment.isIsAvailable()) {
                    seatNumberComboBox.addItem(seatAssignment.getSeatNumber());
                }
            }
        }
        if (seatType.equalsIgnoreCase("Aisle")) {
            for (SeatAssignment seatAssignment : flight.getSeatAssignmentDirectory()) {
                if (seatAssignment.getSeatType().equalsIgnoreCase("Aisle") && seatAssignment.isIsAvailable()) {
                    seatNumberComboBox.addItem(seatAssignment.getSeatNumber());
                }
            }
        }
        seatTypeComboBox.setEnabled(false);
        showSeatsBtn.setEnabled(false);
        seatTypeBtn.setEnabled(true);
        seatNumberComboBox.setEnabled(true);
    }//GEN-LAST:event_showSeatsBtnActionPerformed

    private void seatTypeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatTypeBtnActionPerformed
        // TODO add your handling code here:
        seatTypeComboBox.setEnabled(true);
        showSeatsBtn.setEnabled(true);
        seatTypeBtn.setEnabled(false);
        seatNumberComboBox.removeAllItems();
        seatNumberComboBox.setEnabled(false);
    }//GEN-LAST:event_seatTypeBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arrivalTextField;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JTextField departureTextField;
    private javax.swing.JTextField durationTextField;
    private javax.swing.JTextField flightNumberTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JButton reserveBtn;
    private javax.swing.JComboBox<String> seatNumberComboBox;
    private javax.swing.JButton seatTypeBtn;
    private javax.swing.JComboBox<String> seatTypeComboBox;
    private javax.swing.JButton showSeatsBtn;
    private javax.swing.JTextField timeTextField;
    private javax.swing.JTextField usernameTxtField;
    // End of variables declaration//GEN-END:variables
}
