/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Aircraft;
import Business.Airliner;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ketanmalik
 */
public class ViewAirliner extends javax.swing.JPanel {

    /**
     * Creates new form ViewAirliner
     */
    private Airliner airlineDirectory;
    private JPanel displayPanel;
    private String mode;
    private Aircraft updatedInfo;

    public ViewAirliner(Airliner airlineDirectory, JPanel displayPanel) {
        initComponents();
        this.airlineDirectory = airlineDirectory;
        this.displayPanel = displayPanel;
        populateTable();
        enableFields(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        searchAircraftTxtField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        aircraftTbl = new javax.swing.JTable();
        viewAircraftBtn = new javax.swing.JButton();
        deleteAircraftBtn = new javax.swing.JButton();
        newAircraftBtn = new javax.swing.JButton();
        confirmBtn = new javax.swing.JButton();
        serialNoTxtField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        modelNoTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        entertainmentCheckBox = new javax.swing.JCheckBox();
        wifiCheckBox = new javax.swing.JCheckBox();
        updateAircraft = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        searchBtn.setText("Search by Name");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        aircraftTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial Number", "Name", "Model Number", "Entertainment", "WiFi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(aircraftTbl);
        if (aircraftTbl.getColumnModel().getColumnCount() > 0) {
            aircraftTbl.getColumnModel().getColumn(0).setResizable(false);
            aircraftTbl.getColumnModel().getColumn(1).setResizable(false);
            aircraftTbl.getColumnModel().getColumn(2).setResizable(false);
            aircraftTbl.getColumnModel().getColumn(3).setResizable(false);
            aircraftTbl.getColumnModel().getColumn(4).setResizable(false);
        }

        viewAircraftBtn.setText("View Flights");
        viewAircraftBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAircraftBtnActionPerformed(evt);
            }
        });

        deleteAircraftBtn.setText("Delete Aircraft");
        deleteAircraftBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAircraftBtnActionPerformed(evt);
            }
        });

        newAircraftBtn.setText("New Aircraft");
        newAircraftBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAircraftBtnActionPerformed(evt);
            }
        });

        confirmBtn.setText("Confirm");
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Serial Number:");

        jLabel2.setText("Name:");

        jLabel3.setText("Model:");

        jLabel4.setText("Entertainment:");

        jLabel5.setText("WiFi:");

        updateAircraft.setText("Update Aircraft");
        updateAircraft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAircraftActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("FLEET DIRECTORY");
        jLabel6.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)))
                            .addComponent(searchBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchAircraftTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modelNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(nameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(wifiCheckBox))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(serialNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(entertainmentCheckBox)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deleteAircraftBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewAircraftBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newAircraftBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateAircraft, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(viewAircraftBtn)
                        .addGap(18, 18, 18)
                        .addComponent(deleteAircraftBtn)
                        .addGap(18, 18, 18)
                        .addComponent(newAircraftBtn)
                        .addGap(18, 18, 18)
                        .addComponent(updateAircraft)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBtn)
                    .addComponent(searchAircraftTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(entertainmentCheckBox)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(serialNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(nameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(wifiCheckBox)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(modelNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(confirmBtn)
                .addContainerGap(127, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void enableFields(boolean bool) {
        serialNoTxtField.setEnabled(bool);
        nameTxtField.setEnabled(bool);
        modelNoTxtField.setEnabled(bool);
        entertainmentCheckBox.setEnabled(bool);
        wifiCheckBox.setEnabled(bool);
        confirmBtn.setEnabled(bool);
    }

    public void clearFields() {
        serialNoTxtField.setText("");
        nameTxtField.setText("");
        modelNoTxtField.setText("");
        entertainmentCheckBox.setSelected(false);
        wifiCheckBox.setSelected(false);
    }

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        displayPanel.remove(this);
        CardLayout layout = (CardLayout) displayPanel.getLayout();
        Component[] comps = displayPanel.getComponents();
        for (Component comp : comps) {
            if (comp instanceof ManageAirliners) {
                ManageAirliners ma = (ManageAirliners) comp;
                ma.populateTable();
            }
        }
        layout.previous(displayPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void deleteAircraftBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAircraftBtnActionPerformed
        // TODO add your handling code here:
        enableFields(false);
        clearFields();
        int selectedRow = aircraftTbl.getSelectedRow();
        if (selectedRow >= 0) {
            Aircraft af = (Aircraft) aircraftTbl.getValueAt(selectedRow, 0);
            airlineDirectory.deleteAircraft(af);
            populateTable();
            JOptionPane.showMessageDialog(null, "Aircraft deleted from airliner");
        } else {
            JOptionPane.showMessageDialog(null, "Please select an aircraft to delete");
        }
    }//GEN-LAST:event_deleteAircraftBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        enableFields(false);
        clearFields();
        String searchTerm = searchAircraftTxtField.getText();
        if (searchTerm == null || searchTerm.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter an aircraft name to search");
            populateTable();
        } else {
            ArrayList<Aircraft> found = airlineDirectory.searchAircraft(searchTerm);
            if (found == null) {
                JOptionPane.showMessageDialog(null, "No aircraft found with provided name");
            } else {
                DefaultTableModel dtm = (DefaultTableModel) aircraftTbl.getModel();
                dtm.setRowCount(0);

                for (Aircraft e : found) {
                    Object row[] = new Object[5];
                    row[0] = e;
                    row[1] = e.getName();
                    row[2] = e.getModel();
                    row[3] = e.isHasEntertainment() ? "Yes" : "No";
                    row[4] = e.isHasWifi() ? "Yes" : "No";
                    dtm.addRow(row);
                }
            }
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        // TODO add your handling code here:
        try {
            Integer.parseInt(serialNoTxtField.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please enter valid Serial Number");
            return;
        }
        String name = nameTxtField.getText();
        if (name == null || name.equals("") || !isValidString(name)) {
            JOptionPane.showMessageDialog(null, "Please enter valid name");
            return;
        }
        String model = modelNoTxtField.getText();
        if (model == null || model.equals("") || !isValidString(model)) {
            JOptionPane.showMessageDialog(null, "Please enter valid model");
            return;
        }
        if (name == null || name.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter name");
            return;
        }
        boolean entertainment = entertainmentCheckBox.isSelected();
        boolean wifi = wifiCheckBox.isSelected();

        if (mode == "new") {
            for (Aircraft e : airlineDirectory.getAircraftDirectory()) {
                if (e.getSerialNo() == Integer.parseInt(serialNoTxtField.getText())) {
                    JOptionPane.showMessageDialog(null, "Aircraft with provided serial number already exists");
                    return;
                }
            }
//            Aircraft aircraft = new Aircraft(Integer.parseInt(serialNoTxtField.getText()), name, model, entertainment, wifi);
//            airlineDirectory.getAircraftDirectory().add(aircraft);
            Aircraft aircraft = airlineDirectory.addAircraft();
            aircraft.setSerialNo(Integer.parseInt(serialNoTxtField.getText()));
            aircraft.setName(name);
            aircraft.setModelNo(model);
            aircraft.setHasEntertainment(entertainment);
            aircraft.setHasWifi(wifi);
            JOptionPane.showMessageDialog(null, "Aircraft added to fleet");
        } else {
            updatedInfo.setSerialNo(Integer.parseInt(serialNoTxtField.getText()));
            updatedInfo.setName(name);
            updatedInfo.setModelNo(model);
            updatedInfo.setHasEntertainment(entertainment);
            updatedInfo.setHasWifi(wifi);
            JOptionPane.showMessageDialog(null, "Aircraft information updated in directory");
        }
        populateTable();
        enableFields(false);
        clearFields();
    }//GEN-LAST:event_confirmBtnActionPerformed

    private void newAircraftBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAircraftBtnActionPerformed
        // TODO add your handling code here:
        enableFields(true);
        clearFields();
        mode = "new";
    }//GEN-LAST:event_newAircraftBtnActionPerformed

    private void viewAircraftBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAircraftBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = aircraftTbl.getSelectedRow();
        if (selectedRow >= 0) {
            System.out.println("Interface.ViewAirliner.viewAircraftBtnActionPerformed()");
            Aircraft af = (Aircraft) aircraftTbl.getValueAt(selectedRow, 0);
            ViewAircraft viewAircraft = new ViewAircraft(af, displayPanel);
            CardLayout layout = (CardLayout) displayPanel.getLayout();
            displayPanel.add("viewAircraft", viewAircraft);
            layout.next(displayPanel);
        } else {
            JOptionPane.showMessageDialog(null, "Please select an airplane to view");
        }
    }//GEN-LAST:event_viewAircraftBtnActionPerformed

    private void updateAircraftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAircraftActionPerformed
        // TODO add your handling code here:
        int selectedRow = aircraftTbl.getSelectedRow();
        if (selectedRow >= 0) {
            mode = "update";
            Aircraft aircraft = (Aircraft) aircraftTbl.getValueAt(selectedRow, 0);
            serialNoTxtField.setText(aircraft.getSerialNo() + "");
            nameTxtField.setText(aircraft.getName() + "");
            modelNoTxtField.setText(aircraft.getModel() + "");
            entertainmentCheckBox.setSelected(aircraft.isHasEntertainment());
            wifiCheckBox.setSelected(aircraft.isHasWifi());
            enableFields(true);
            updatedInfo = aircraft;
        } else {
            enableFields(false);
            clearFields();
            JOptionPane.showMessageDialog(null, "Please select an aircraft to update");
        }
    }//GEN-LAST:event_updateAircraftActionPerformed

    public boolean isValidString(String str) {
        Pattern p = Pattern.compile("^[a-zA-Z0-9]+$");
        Matcher m = p.matcher(str);
        return m.matches();
    }

    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) aircraftTbl.getModel();
        dtm.setRowCount(0);
        ArrayList<Aircraft> temp = airlineDirectory.getAircraftDirectory();
        airlineDirectory.setNoOfAircrafts(temp.size());
        for (Aircraft e : airlineDirectory.getAircraftDirectory()) {

            Object row[] = new Object[5];
            row[0] = e;
            row[1] = e.getName();
            row[2] = e.getModel();
            row[3] = e.isHasEntertainment() ? "Yes" : "No";
            row[4] = e.isHasWifi() ? "Yes" : "No";
            dtm.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable aircraftTbl;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JButton deleteAircraftBtn;
    private javax.swing.JCheckBox entertainmentCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField modelNoTxtField;
    private javax.swing.JTextField nameTxtField;
    private javax.swing.JButton newAircraftBtn;
    private javax.swing.JTextField searchAircraftTxtField;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField serialNoTxtField;
    private javax.swing.JButton updateAircraft;
    private javax.swing.JButton viewAircraftBtn;
    private javax.swing.JCheckBox wifiCheckBox;
    // End of variables declaration//GEN-END:variables
}
